export const AUTH_USER_CREATE_INIT = 'AUTH_USER_CREATE_INIT';
export const AUTH_USER_CREATE_FAIL = 'AUTH_USER_CREATE_FAIL';
export const AUTH_USER_CREATE_SUCCESS = 'AUTH_USER_CREATE_SUCCESS';

export const AUTH_CHANGE_PASSWORD_INIT = 'AUTH_CHANGE_PASSWORD_INIT';
export const AUTH_CHANGE_PASSWORD_FAIL = 'AUTH_CHANGE_PASSWORD_FAIL';
export const AUTH_CHANGE_PASSWORD_SUCCESS = 'AUTH_CHANGE_PASSWORD_SUCCESS';

export const AUTH_LOGOUT_INIT = 'AUTH_LOGOUT_INIT';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_LOGOUT_FAIL = 'AUTH_LOGOUT_FAIL';

export const AUTH_USER_LOGIN_INIT = 'AUTH_USER_LOGIN_INIT';
export const AUTH_USER_LOGIN_FAIL = 'AUTH_USER_LOGIN_FAIL';
export const AUTH_USER_LOGIN_SUCCESS = 'AUTH_USER_LOGIN_SUCCESS';

export const AUTH_USER_INIT = 'AUTH_USER_INIT';
export const AUTH_USER_FAIL = 'AUTH_USER_FAIL';
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';

