export const AUTH_USER_CREATE_INIT = 'AUTH_USER_CREATE_INIT';
export const AUTH_USER_CREATE_FAIL = 'AUTH_USER_CREATE_FAIL';
export const AUTH_USER_CREATE_SUCCESS = 'AUTH_USER_CREATE_SUCCESS';

export const AUTH_CHANGE_PASSWORD_INIT = 'AUTH_CHANGE_PASSWORD_INIT';
export const AUTH_CHANGE_PASSWORD_FAIL = 'AUTH_CHANGE_PASSWORD_FAIL';
export const AUTH_CHANGE_PASSWORD_SUCCESS = 'AUTH_CHANGE_PASSWORD_SUCCESS';

export const AUTH_LOGOUT_INIT = 'AUTH_LOGOUT_INIT';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_LOGOUT_FAIL = 'AUTH_LOGOUT_FAIL';

export const AUTH_USER_LOGIN_INIT = 'AUTH_USER_LOGIN_INIT';
export const AUTH_USER_LOGIN_FAIL = 'AUTH_USER_LOGIN_FAIL';
export const AUTH_USER_LOGIN_SUCCESS = 'AUTH_USER_LOGIN_SUCCESS';

export const AUTH_USER_INIT = 'AUTH_USER_INIT';
export const AUTH_USER_FAIL = 'AUTH_USER_FAIL';
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';

export const USER_FETCH_DEVICE_INFO_INIT = 'USER_FETCH_DATA_INIT';
export const USER_FETCH_DEVICE_INFO_FAIL = 'USER_FETCH_DEVICE_INFO_FAIL';
export const USER_FETCH_DEVICE_INFO_SUCCESS = 'USER_FETCH_DEVICE_INFO_SUCCESS';

export const USER_DEVICE_SWITCH_INIT = 'USER_DEVICE_SWITCH_INIT';
export const USER_DEVICE_SWITCH_FAIL = 'USER_DEVICE_SWITCH_FAIL';
export const USER_DEVICE_SWITCH_SUCCESS = 'USER_DEVICE_SWITCH_SUCCESS';

export const USER_ADD_DEVICE_INIT = 'USER_ADD_DEVICE_INIT';
export const USER_ADD_DEVICE_FAIL = 'USER_ADD_DEVICE_FAIL';
export const USER_ADD_DEVICE_SUCCESS = 'USER_ADD_DEVICE_SUCCESS';

export const USER_CHANGE_COLOR_INIT = 'USER_CHANGE_COLOR_INIT';
export const USER_CHANGE_COLOR_FAIL = 'USER_CHANGE_COLOR_FAIL';
export const USER_CHANGE_COLOR_SUCCESS = 'USER_CHANGE_COLOR_SUCCESS';
